services:
  - docker

script:
  - docker build jenkins
  - docker build jenkins-slave/maven
  - docker build jenkins-slave/nodejs
  - docker build s2i-jdk8-maven3-subatomic
  - docker build s2i-nodejs-nginx-subatomic